version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.main.dev
    ports:
      # <outside-world-can-access-to-the-container-at-port>:<container-port>
      # <container-port> is defined in package.json start by webpack
      - '3002:3002'
    env_file:
      - ./env/.env.dev
  mfe:
    build:
      context: .
      dockerfile: Dockerfile.mfe.dev
    ports:
      # <outside-world-can-access-to-the-container-at-port>:<container-port>
      # <container-port> is defined in package.json start by webpack
      - '3032:3032'
    env_file:
      - ./env/.env.dev
